# Generated by Django 4.1.5 on 2023-02-17 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Manga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('author', models.CharField(max_length=120)),
                ('total_chapters', models.IntegerField()),
                ('newest_chapter', models.IntegerField()),
                ('completed', models.BooleanField(default=False)),
                ('currently_reading', models.BooleanField(default=False)),
                ('genre', models.ManyToManyField(to='manga2.genres')),
            ],
        ),
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Metrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_mangas_read', models.IntegerField()),
                ('weekly_chapter_avg', models.IntegerField()),
                ('most_daily_chapters', models.IntegerField()),
                ('top_5_mangas', models.ManyToManyField(to='manga2.manga')),
            ],
        ),
        migrations.AddField(
            model_name='manga',
            name='rating',
            field=models.ManyToManyField(to='manga2.ratings'),
        ),
    ]
