# Generated by Django 4.1.5 on 2023-02-17 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manga2', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Genres',
            new_name='Genre',
        ),
        migrations.RenameModel(
            old_name='Metrics',
            new_name='Metric',
        ),
        migrations.RenameModel(
            old_name='Ratings',
            new_name='Rating',
        ),
    ]
