# Generated by Django 4.1.5 on 2023-02-17 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga2', '0003_genre_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
