# Generated by Django 4.1.5 on 2023-02-28 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga2', '0004_alter_genre_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manga',
            old_name='total_chapters',
            new_name='last_read_chapter',
        ),
        migrations.AddField(
            model_name='manga',
            name='url',
            field=models.CharField(default=0, max_length=120),
            preserve_default=False,
        ),
    ]
